module.exports = {
  OTP: {
    REGISTRATION: "REGISTRATION",
    AUTHENTICATION: "AUTHENTICATION",
  },
  COUPON_TYPE: {
    PERCENTAGE: "PERCENTAGE",
    FLAT_VALUE: "FLAT_VALUE",
  },
  ORDER_STATUS: {
    RECEIVED: "RECEIVED",
    DISPATCHED: "DISPATCHED",
    DELIVERED: "DELIVERED",
    CANCELLED: "CANCELLED",
  },
  PAYMENT_STATUS: {
    SUCCEEDED: "succeeded",
    FAILED: "failed"
  }
};
