export const GET_BANNERS_REQUEST = "GET_BANNERS_REQUEST"
export const GET_BANNERS_SUCCESS = "GET_BANNERS_SUCCESS"
export const GET_BANNERS_FAIL = "GET_BANNERS_FAIL"

export const UPDATE_BANNERS_REQUEST = "UPDATE_BANNERS_REQUEST"
export const UPDATE_BANNERS_SUCCESS = "UPDATE_BANNERS_SUCCESS"
export const UPDATE_BANNERS_FAIL = "UPDATE_BANNERS_FAIL"
export const UPDATE_BANNERS_RESET = "UPDATE_BANNERS_RESET"

export const CLEAR_ERRORS = "CLEAR_ERRORS"