export const GET_SUB_CATEGORIES_REQUEST = "GET_SUB_CATEGORIES_REQUEST"
export const GET_SUB_CATEGORIES_SUCCESS = "GET_SUB_CATEGORIES_SUCCESS"
export const GET_SUB_CATEGORIES_FAIL = "GET_SUB_CATEGORIES_FAIL"

export const NEW_SUB_CATEGORY_REQUEST = "NEW_SUB_CATEGORY_REQUEST"
export const NEW_SUB_CATEGORY_SUCCESS = "NEW_SUB_CATEGORY_SUCCESS"
export const NEW_SUB_CATEGORY_FAIL = "NEW_SUB_CATEGORY_FAIL"
export const NEW_SUB_CATEGORY_RESET = "NEW_SUB_CATEGORY_RESET"

export const UPDATE_SUB_CATEGORY_REQUEST = "UPDATE_SUB_CATEGORY_REQUEST"
export const UPDATE_SUB_CATEGORY_SUCCESS = "UPDATE_SUB_CATEGORY_SUCCESS"
export const UPDATE_SUB_CATEGORY_FAIL = "UPDATE_SUB_CATEGORY_FAIL"
export const UPDATE_SUB_CATEGORY_RESET = "UPDATE_SUB_CATEGORY_RESET"

export const DELETE_SUB_CATEGORY_REQUEST = "DELETE_SUB_CATEGORY_REQUEST"
export const DELETE_SUB_CATEGORY_SUCCESS = "DELETE_SUB_CATEGORY_SUCCESS"
export const DELETE_SUB_CATEGORY_FAIL = "DELETE_SUB_CATEGORY_FAIL"
export const DELETE_SUB_CATEGORY_RESET = "DELETE_SUB_CATEGORY_RESET"

export const SUB_CATEGORY_DETAILS_REQUEST = "SUB_CATEGORY_DETAILS_REQUEST"
export const SUB_CATEGORY_DETAILS_SUCCESS = "SUB_CATEGORY_DETAILS_SUCCESS"
export const SUB_CATEGORY_DETAILS_FAIL = "SUB_CATEGORY_DETAILS_FAIL"

export const SUB_CATEGORIES_FOR_CATEGORY_REQUEST = "SUB_CATEGORIES_FOR_CATEGORY_REQUEST"
export const SUB_CATEGORIES_FOR_CATEGORY_SUCCESS = "SUB_CATEGORIES_FOR_CATEGORY_SUCCESS"
export const SUB_CATEGORIES_FOR_CATEGORY_FAIL = "SUB_CATEGORIES_FOR_CATEGORY_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"